# Generated by Django 5.1.15 on 2026-08-06 01:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_studies', '0001_initial'),
        ('cms', '0001_initial'),
        ('industries', '0001_initial'),
        ('insights', '0001_initial'),
        ('packages_catalog', '0001_initial'),
        ('services_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('location', models.CharField(choices=[('header_primary', 'Header primary'), ('header_secondary', 'Header secondary'), ('footer_primary', 'Footer primary'), ('footer_secondary', 'Footer secondary'), ('footer_legal', 'Footer legal'), ('mobile', 'Mobile'), ('dashboard', 'Dashboard'), ('client_portal', 'Client portal'), ('custom', 'Custom')], db_index=True, default='custom', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationMenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(db_index=True, max_length=150)),
                ('link_type', models.CharField(choices=[('internal', 'Internal URL'), ('external', 'External URL'), ('route', 'Named route'), ('cms_page', 'CMS page'), ('service', 'Service'), ('package', 'Package'), ('industry', 'Industry'), ('insight', 'Insight'), ('case_study', 'Case study'), ('careers', 'Careers'), ('contact', 'Contact'), ('quote', 'Request quote'), ('custom', 'Custom')], db_index=True, default='internal', max_length=30)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('route_name', models.CharField(blank=True, max_length=200)),
                ('route_parameters', models.JSONField(blank=True, default=dict)),
                ('visibility', models.CharField(choices=[('everyone', 'Everyone'), ('guests', 'Guests only'), ('authenticated', 'Authenticated users'), ('staff', 'Staff only'), ('superuser', 'Superusers only')], db_index=True, default='everyone', max_length=30)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('css_class', models.CharField(blank=True, max_length=200)),
                ('target_blank', models.BooleanField(default=False)),
                ('rel_attribute', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='case_studies.casestudy')),
                ('cms_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='cms.page')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='industries.industry')),
                ('insight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='insights.insightarticle')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.navigationmenu')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='packages_catalog.package')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.navigationmenuitem')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='services_catalog.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'label'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='navigationmenu',
            index=models.Index(fields=['location', 'is_active'], name='navigation__locatio_7c91eb_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationmenu',
            index=models.Index(fields=['is_public', 'sort_order'], name='navigation__is_publ_d54344_idx'),
        ),
        migrations.AddConstraint(
            model_name='navigationmenu',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_navigation_menu_name'),
        ),
        migrations.AddIndex(
            model_name='navigationmenuitem',
            index=models.Index(fields=['menu', 'parent', 'sort_order'], name='navigation__menu_id_fc76bc_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationmenuitem',
            index=models.Index(fields=['menu', 'is_active'], name='navigation__menu_id_632278_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationmenuitem',
            index=models.Index(fields=['visibility', 'is_active'], name='navigation__visibil_9ce591_idx'),
        ),
        migrations.AddIndex(
            model_name='navigationmenuitem',
            index=models.Index(fields=['is_featured', 'sort_order'], name='navigation__is_feat_e895d8_idx'),
        ),
    ]
