# Generated by Django 5.1.15 on 2026-08-06 01:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicWebsiteSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_type', models.CharField(choices=[('bootstrap', 'Bootstrap'), ('homepage', 'Homepage'), ('catalog', 'Catalog'), ('content', 'Content'), ('sitemap', 'Sitemap')], db_index=True, max_length=30)),
                ('environment', models.CharField(db_index=True, default='production', max_length=30)),
                ('version', models.PositiveBigIntegerField(db_index=True, default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version', '-generated_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['snapshot_type', 'environment', 'is_active'], name='public_webs_snapsho_f908f9_idx'), models.Index(fields=['expires_at', 'is_active'], name='public_webs_expires_52558c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('snapshot_type', 'environment', 'version'), name='unique_public_snapshot_version')],
            },
        ),
    ]
