# Generated by Django 5.1.15 on 2026-08-06 01:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON'), ('email', 'Email'), ('url', 'URL'), ('color', 'Color'), ('media', 'Media asset')], db_index=True, default='string', max_length=30)),
                ('environment', models.CharField(choices=[('global', 'Global'), ('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], db_index=True, default='global', max_length=30)),
                ('value', models.TextField(blank=True)),
                ('json_value', models.JSONField(blank=True, default=dict)),
                ('default_value', models.TextField(blank=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_editable', models.BooleanField(db_index=True, default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_setting_usages', to='media_library.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings', to='website_settings.websitesettinggroup')),
            ],
            options={
                'ordering': ('group__sort_order', 'sort_order', 'key'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='websitesettinggroup',
            index=models.Index(fields=['is_active', 'sort_order'], name='website_set_is_acti_f63ca7_idx'),
        ),
        migrations.AddConstraint(
            model_name='websitesettinggroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_website_setting_group_name'),
        ),
        migrations.AddIndex(
            model_name='websitesetting',
            index=models.Index(fields=['group', 'is_active'], name='website_set_group_i_e24b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesetting',
            index=models.Index(fields=['environment', 'is_active'], name='website_set_environ_f0253d_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesetting',
            index=models.Index(fields=['is_public', 'is_active'], name='website_set_is_publ_826ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesetting',
            index=models.Index(fields=['value_type', 'is_active'], name='website_set_value_t_64a1b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='websitesetting',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('key', 'environment'), name='unique_active_website_setting_key_environment'),
        ),
    ]
