# Generated by Django 5.1.15 on 2026-08-05 21:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('key', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('generic', 'Generic'), ('privacy', 'Privacy Policy'), ('terms', 'Terms and Conditions'), ('cookie', 'Cookie Policy'), ('contact', 'Contact')], db_index=True, default='generic', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('template_name', models.CharField(default='pages/default.html', max_length=150)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='cms/pages/%Y/%m/')),
                ('is_indexable', models.BooleanField(default=True)),
                ('is_visible_in_navigation', models.BooleanField(default=False)),
                ('navigation_label', models.CharField(blank=True, max_length=100)),
                ('navigation_order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('current_revision_number', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('navigation_order', 'title'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('section_key', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_placements', to='cms.contentblock')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='cms.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=250)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], max_length=20)),
                ('change_summary', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_page_revisions', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='cms.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-revision_number',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=170)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('open_graph_title', models.CharField(blank=True, max_length=100)),
                ('open_graph_description', models.CharField(blank=True, max_length=200)),
                ('open_graph_image', models.ImageField(blank=True, null=True, upload_to='cms/seo/open-graph/%Y/%m/')),
                ('twitter_title', models.CharField(blank=True, max_length=100)),
                ('twitter_description', models.CharField(blank=True, max_length=200)),
                ('twitter_image', models.ImageField(blank=True, null=True, upload_to='cms/seo/twitter/%Y/%m/')),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='cms.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived'), ('restored', 'Revision Restored')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishing_events', to='cms.page')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('destination_url', models.CharField(max_length=1000)),
                ('redirect_type', models.PositiveSmallIntegerField(choices=[(301, 'Permanent'), (302, 'Temporary'), (308, 'Permanent — Preserve Method')], default=301)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hit_count', models.PositiveBigIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('source_path',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['is_active', 'name'], name='cms_content_is_acti_e35bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status', 'published_at'], name='cms_page_status_caf16a_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['page_type', 'status'], name='cms_page_page_ty_165c09_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_visible_in_navigation', 'navigation_order'], name='cms_page_is_visi_7c688c_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecontentblock',
            index=models.Index(fields=['page', 'section_key', 'sort_order'], name='cms_pagecon_page_id_0bc3cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagecontentblock',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('page', 'content_block', 'section_key'), name='unique_active_page_content_block'),
        ),
        migrations.AddIndex(
            model_name='pagerevision',
            index=models.Index(fields=['page', 'revision_number'], name='cms_pagerev_page_id_4f8057_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('page', 'revision_number'), name='unique_active_page_revision_number'),
        ),
        migrations.AddIndex(
            model_name='publishingevent',
            index=models.Index(fields=['page', 'created_at'], name='cms_publish_page_id_63190f_idx'),
        ),
        migrations.AddIndex(
            model_name='publishingevent',
            index=models.Index(fields=['event_type', 'created_at'], name='cms_publish_event_t_4e059c_idx'),
        ),
        migrations.AddIndex(
            model_name='redirect',
            index=models.Index(fields=['is_active', 'source_path'], name='cms_redirec_is_acti_7f8871_idx'),
        ),
    ]
