# Generated by Django 5.1.15 on 2026-08-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('login_success', 'Login success'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('password_changed', 'Password changed'), ('role_assigned', 'Role assigned'), ('role_removed', 'Role removed'), ('permission_changed', 'Permission changed'), ('record_created', 'Record created'), ('record_updated', 'Record updated'), ('record_deleted', 'Record deleted'), ('security_event', 'Security event')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=20)),
                ('module', models.CharField(db_index=True, max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=150)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['module', 'event_type'], name='audit_audit_module_9f95b0_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx'), models.Index(fields=['severity', 'created_at'], name='audit_audit_severit_effc12_idx')],
            },
        ),
    ]
