import { z } from "zod";

import {
  campaignStatuses,
  subscriberSources,
  subscriberStatuses,
} from "./types";

const nullableDateTimeSchema = z.string().nullable();
const metadataSchema = z.record(z.string(), z.unknown());

export const newsletterListSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  description: z.string(),
  is_default: z.boolean(),
  is_public: z.boolean(),
  is_active: z.boolean(),
  sort_order: z.number().int(),
  subscriber_count: z.number().int().nonnegative(),
});

export const newsletterTagSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  slug: z.string(),
  description: z.string(),
  color: z.string(),
  is_active: z.boolean(),
  subscriber_count: z.number().int().nonnegative(),
});

export const subscriberSchema = z.object({
  id: z.string().uuid(),
  email: z.string(),
  first_name: z.string(),
  last_name: z.string(),
  full_name: z.string(),
  company_name: z.string(),
  phone: z.string(),
  country: z.string(),
  language: z.string(),
  status: z.enum(subscriberStatuses),
  source: z.enum(subscriberSources),
  source_reference: z.string(),
  consent_given: z.boolean(),
  subscribed_at: z.string(),
  confirmed_at: nullableDateTimeSchema,
  unsubscribed_at: nullableDateTimeSchema,
  confirmation_token: z.string(),
  unsubscribe_token: z.string(),
  bounce_count: z.number().int().nonnegative(),
  last_bounced_at: nullableDateTimeSchema,
  last_email_sent_at: nullableDateTimeSchema,
  metadata: metadataSchema,
  can_receive_email: z.boolean(),
  lists: z.array(newsletterListSchema),
  tags: z.array(newsletterTagSchema),
  created_at: z.string(),
  updated_at: z.string(),
});

export const campaignRecipientSchema = z.object({
  id: z.string().uuid(),
  subscriber_id: z.string().uuid().nullable(),
  email: z.string(),
  first_name: z.string(),
  last_name: z.string(),
  status: z.string(),
  queued_at: nullableDateTimeSchema,
  sent_at: nullableDateTimeSchema,
  delivered_at: nullableDateTimeSchema,
  opened_at: nullableDateTimeSchema,
  clicked_at: nullableDateTimeSchema,
  bounced_at: nullableDateTimeSchema,
  complained_at: nullableDateTimeSchema,
  unsubscribed_at: nullableDateTimeSchema,
  failed_at: nullableDateTimeSchema,
  failure_reason: z.string(),
  provider_message_id: z.string(),
  open_count: z.number().int().nonnegative(),
  click_count: z.number().int().nonnegative(),
});

export const newsletterCampaignSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  subject: z.string(),
  preview_text: z.string(),
  from_name: z.string(),
  from_email: z.string(),
  reply_to_email: z.string(),
  html_content: z.string(),
  text_content: z.string(),
  status: z.enum(campaignStatuses),
  scheduled_for: nullableDateTimeSchema,
  queued_at: nullableDateTimeSchema,
  sending_started_at: nullableDateTimeSchema,
  sent_at: nullableDateTimeSchema,
  completed_at: nullableDateTimeSchema,
  failure_reason: z.string(),
  recipient_count: z.number().int().nonnegative(),
  queued_count: z.number().int().nonnegative(),
  sent_count: z.number().int().nonnegative(),
  delivered_count: z.number().int().nonnegative(),
  opened_count: z.number().int().nonnegative(),
  clicked_count: z.number().int().nonnegative(),
  bounced_count: z.number().int().nonnegative(),
  complained_count: z.number().int().nonnegative(),
  unsubscribed_count: z.number().int().nonnegative(),
  failed_count: z.number().int().nonnegative(),
  open_rate: z.number(),
  click_rate: z.number(),
  metadata: metadataSchema,
  lists: z.array(newsletterListSchema),
  tags: z.array(newsletterTagSchema),
  created_at: z.string(),
  updated_at: z.string(),
});

export const newsletterDashboardSchema = z.object({
  total_subscribers: z.number().int().nonnegative(),
  active_subscribers: z.number().int().nonnegative(),
  pending_subscribers: z.number().int().nonnegative(),
  unsubscribed_subscribers: z.number().int().nonnegative(),
  bounced_subscribers: z.number().int().nonnegative(),
  total_campaigns: z.number().int().nonnegative(),
  draft_campaigns: z.number().int().nonnegative(),
  scheduled_campaigns: z.number().int().nonnegative(),
  sent_campaigns: z.number().int().nonnegative(),
  total_emails_sent: z.number().int().nonnegative(),
  total_delivered: z.number().int().nonnegative(),
  total_opened: z.number().int().nonnegative(),
  total_clicked: z.number().int().nonnegative(),
});
