# Generated by Django 5.1.15 on 2026-08-05 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('services_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=350)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('hero_title', models.CharField(blank=True, max_length=250)),
                ('hero_description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('solutions', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('cta_title', models.CharField(blank=True, max_length=200)),
                ('cta_text', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('current_revision_number', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_hero_usages', to='media_library.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrySeo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=170)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('open_graph_title', models.CharField(blank=True, max_length=100)),
                ('open_graph_description', models.CharField(blank=True, max_length=200)),
                ('twitter_title', models.CharField(blank=True, max_length=100)),
                ('twitter_description', models.CharField(blank=True, max_length=200)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='industries.industry')),
                ('open_graph_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_open_graph_usages', to='media_library.mediaasset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='industries.industry')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_links', to='services_catalog.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='industry',
            name='services',
            field=models.ManyToManyField(related_name='industries', through='industries.IndustryService', to='services_catalog.service'),
        ),
        migrations.CreateModel(
            name='IndustryFaq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='industries.industry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['industry', 'sort_order'], name='industries__industr_a9da68_idx')],
            },
        ),
        migrations.CreateModel(
            name='IndustryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='industries.industry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-revision_number',),
                'abstract': False,
                'indexes': [models.Index(fields=['industry', 'revision_number'], name='industries__industr_eac0db_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('industry', 'revision_number'), name='unique_active_industry_revision')],
            },
        ),
        migrations.AddIndex(
            model_name='industryservice',
            index=models.Index(fields=['industry', 'sort_order'], name='industries__industr_fd4145_idx'),
        ),
        migrations.AddConstraint(
            model_name='industryservice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('industry', 'service'), name='unique_active_industry_service'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['status', 'published_at'], name='industries__status_d27b10_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['is_featured', 'sort_order'], name='industries__is_feat_619582_idx'),
        ),
        migrations.AddIndex(
            model_name='industry',
            index=models.Index(fields=['is_active', 'sort_order'], name='industries__is_acti_13ff34_idx'),
        ),
    ]
