# Generated by Django 5.1.15 on 2026-08-05 21:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_library.mediafolder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('file', models.FileField(upload_to='media-library/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('pdf', 'PDF'), ('icon', 'Icon'), ('logo', 'Logo'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('mime_type', models.CharField(blank=True, max_length=150)),
                ('extension', models.CharField(blank=True, max_length=20)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('caption', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=128)),
                ('is_optimized', models.BooleanField(default=False)),
                ('optimized_file', models.FileField(blank=True, null=True, upload_to='media-library/optimized/%Y/%m/')),
                ('webp_file', models.ImageField(blank=True, null=True, upload_to='media-library/webp/%Y/%m/')),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='media_library.mediafolder')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('usage_context', models.CharField(blank=True, max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='media_library.mediaasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='mediafolder',
            index=models.Index(fields=['parent', 'name'], name='media_libra_parent__1265f9_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('parent', 'slug'), name='unique_active_media_folder_slug'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['folder', 'media_type'], name='media_libra_folder__476bfc_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['media_type', 'created_at'], name='media_libra_media_t_49ef35_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['is_public', 'created_at'], name='media_libra_is_publ_636010_idx'),
        ),
        migrations.AddIndex(
            model_name='mediausage',
            index=models.Index(fields=['application', 'model_name', 'object_id'], name='media_libra_applica_4370b7_idx'),
        ),
        migrations.AddIndex(
            model_name='mediausage',
            index=models.Index(fields=['asset', 'created_at'], name='media_libra_asset_i_bfcb3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediausage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('asset', 'application', 'model_name', 'object_id', 'field_name'), name='unique_active_media_usage'),
        ),
    ]
