# Generated by Django 5.1.15 on 2026-08-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['key', 'window_started_at'], name='api_ratelim_key_59a7fa_idx')],
            },
        ),
    ]
