# Generated by Django 5.1.15 on 2026-08-06 00:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('language', models.CharField(db_index=True, default='en', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('active', 'Active'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('suppressed', 'Suppressed')], db_index=True, default='pending', max_length=30)),
                ('source', models.CharField(choices=[('website', 'Website'), ('manual', 'Manual'), ('import', 'Import'), ('contact_form', 'Contact form'), ('quote_form', 'Quote form'), ('careers', 'Careers'), ('client_portal', 'Client portal'), ('other', 'Other')], db_index=True, default='website', max_length=30)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('consent_user_agent', models.TextField(blank=True)),
                ('subscribed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('confirmation_token', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('unsubscribe_token', models.CharField(db_index=True, editable=False, max_length=100, unique=True)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('last_bounced_at', models.DateTimeField(blank=True, null=True)),
                ('last_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-subscribed_at', 'email'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberListMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('newsletter_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='newsletter.newsletterlist')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='newsletter.subscriber')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('newsletter_list__sort_order', 'joined_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='lists',
            field=models.ManyToManyField(related_name='subscribers', through='newsletter.SubscriberListMembership', to='newsletter.newsletterlist'),
        ),
        migrations.CreateModel(
            name='SubscriberTagAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='newsletter.subscriber')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='newsletter.newslettertag')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tag__name', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tags',
            field=models.ManyToManyField(related_name='subscribers', through='newsletter.SubscriberTagAssignment', to='newsletter.newslettertag'),
        ),
        migrations.AddIndex(
            model_name='newsletterlist',
            index=models.Index(fields=['is_active', 'is_public'], name='newsletter__is_acti_4c6cd1_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletterlist',
            index=models.Index(fields=['is_default', 'sort_order'], name='newsletter__is_defa_13a5b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsletterlist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_newsletter_list_name'),
        ),
        migrations.AddConstraint(
            model_name='newslettertag',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_newsletter_tag_name'),
        ),
        migrations.AddIndex(
            model_name='subscriberlistmembership',
            index=models.Index(fields=['newsletter_list', 'joined_at'], name='newsletter__newslet_8a9460_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriberlistmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('subscriber', 'newsletter_list'), name='unique_active_subscriber_list_membership'),
        ),
        migrations.AddConstraint(
            model_name='subscribertagassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('subscriber', 'tag'), name='unique_active_subscriber_tag_assignment'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['status', 'subscribed_at'], name='newsletter__status_11679a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['source', 'status'], name='newsletter__source_2e0de5_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['country', 'status'], name='newsletter__country_16881b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['language', 'status'], name='newsletter__languag_7211ec_idx'),
        ),
    ]
