# Generated by Django 5.1.15 on 2026-08-06 02:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('executive', 'Executive dashboard'), ('crm', 'CRM reporting'), ('sales', 'Sales and quotation reporting'), ('projects', 'Project reporting'), ('tasks', 'Task reporting'), ('finance', 'Finance reporting'), ('content_marketing', 'Content and marketing reporting'), ('team', 'Team reporting'), ('complete', 'Complete dashboard report')], db_index=True, max_length=40)),
                ('period_preset', models.CharField(choices=[('today', 'Today'), ('this_week', 'This week'), ('this_month', 'This month'), ('this_quarter', 'This quarter'), ('this_year', 'This year'), ('last_7_days', 'Last 7 days'), ('last_30_days', 'Last 30 days'), ('last_90_days', 'Last 90 days'), ('custom', 'Custom')], db_index=True, default='this_month', max_length=30)),
                ('date_from', models.DateField(blank=True, db_index=True, null=True)),
                ('date_to', models.DateField(blank=True, db_index=True, null=True)),
                ('environment', models.CharField(db_index=True, default='production', max_length=30)),
                ('version', models.PositiveBigIntegerField(db_index=True, default=1)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('checksum', models.CharField(blank=True, db_index=True, max_length=64)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version', '-generated_at'),
                'abstract': False,
                'indexes': [models.Index(fields=['report_type', 'environment', 'is_active'], name='dash_report_active_idx'), models.Index(fields=['period_preset', 'date_from', 'date_to'], name='dash_report_period_idx'), models.Index(fields=['expires_at', 'is_active'], name='dash_report_expiry_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('report_type', 'period_preset', 'date_from', 'date_to', 'environment', 'version'), name='unique_dashboard_report_snapshot_version'), models.CheckConstraint(condition=models.Q(('date_from__isnull', True), ('date_to__isnull', True), ('date_to__gte', models.F('date_from')), _connector='OR'), name='dashboard_snapshot_valid_date_range')],
            },
        ),
    ]
