# Generated by Django 5.1.15 on 2026-08-06 00:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('crm', '0001_initial'),
        ('packages_catalog', '0001_initial'),
        ('quotations', '0001_initial'),
        ('services_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('website', 'Website'), ('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('email', 'Email'), ('phone', 'Phone'), ('manual', 'Manual'), ('other', 'Other')], db_index=True, default='website', max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal sent'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam'), ('archived', 'Archived')], db_index=True, default='new', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('first_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('internal_summary', models.TextField(blank=True)),
                ('loss_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_enquiries', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_enquiries', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_enquiries', to='crm.lead')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50)),
                ('company_name', models.CharField(blank=True, db_index=True, max_length=200)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('website_url', models.URLField(blank=True)),
                ('project_title', models.CharField(blank=True, max_length=250)),
                ('project_description', models.TextField()),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_currency', models.CharField(default='LKR', max_length=3)),
                ('desired_start_date', models.DateField(blank=True, null=True)),
                ('desired_completion_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('website', 'Website'), ('google', 'Google'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('referral', 'Referral'), ('email', 'Email'), ('phone', 'Phone'), ('manual', 'Manual'), ('other', 'Other')], db_index=True, default='website', max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal_sent', 'Proposal sent'), ('won', 'Won'), ('lost', 'Lost'), ('spam', 'Spam'), ('archived', 'Archived')], db_index=True, default='new', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=20)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('first_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('internal_summary', models.TextField(blank=True)),
                ('loss_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quote_enquiries', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_enquiries', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_enquiries', to='crm.lead')),
                ('preferred_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_enquiries', to='packages_catalog.package')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote_enquiries', to='quotations.quotation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-submitted_at', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnquiryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiry_notes', to=settings.AUTH_USER_MODEL)),
                ('contact_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enquiries.contactenquiry')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('quote_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enquiries.quoteenquiry')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteEnquiryService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('quote_enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='enquiries.quoteenquiry')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_enquiry_links', to='services_catalog.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='quoteenquiry',
            name='required_services',
            field=models.ManyToManyField(related_name='quote_enquiries', through='enquiries.QuoteEnquiryService', to='services_catalog.service'),
        ),
        migrations.AddIndex(
            model_name='contactenquiry',
            index=models.Index(fields=['status', 'submitted_at'], name='enquiries_c_status_c3ce99_idx'),
        ),
        migrations.AddIndex(
            model_name='contactenquiry',
            index=models.Index(fields=['priority', 'status'], name='enquiries_c_priorit_30373a_idx'),
        ),
        migrations.AddIndex(
            model_name='contactenquiry',
            index=models.Index(fields=['assigned_to', 'status'], name='enquiries_c_assigne_9e9ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='contactenquiry',
            index=models.Index(fields=['source', 'submitted_at'], name='enquiries_c_source_d35158_idx'),
        ),
        migrations.AddIndex(
            model_name='contactenquiry',
            index=models.Index(fields=['next_follow_up_at', 'status'], name='enquiries_c_next_fo_ee12ef_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirynote',
            index=models.Index(fields=['contact_enquiry', 'created_at'], name='enquiries_e_contact_8f1d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='enquirynote',
            index=models.Index(fields=['quote_enquiry', 'created_at'], name='enquiries_e_quote_e_3489ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='quoteenquiryservice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('quote_enquiry', 'service'), name='unique_active_quote_enquiry_service'),
        ),
        migrations.AddIndex(
            model_name='quoteenquiry',
            index=models.Index(fields=['status', 'submitted_at'], name='enquiries_q_status_d90dd5_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteenquiry',
            index=models.Index(fields=['priority', 'status'], name='enquiries_q_priorit_68c211_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteenquiry',
            index=models.Index(fields=['assigned_to', 'status'], name='enquiries_q_assigne_c4c841_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteenquiry',
            index=models.Index(fields=['source', 'submitted_at'], name='enquiries_q_source_08b5dc_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteenquiry',
            index=models.Index(fields=['next_follow_up_at', 'status'], name='enquiries_q_next_fo_5b9491_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteenquiry',
            index=models.Index(fields=['country', 'status'], name='enquiries_q_country_95ecfe_idx'),
        ),
    ]
