# Generated by Django 5.1.15 on 2026-08-06 01:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('services_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('employee_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(db_index=True, max_length=200)),
                ('professional_title', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('public_phone', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('short_bio', models.CharField(blank=True, max_length=500)),
                ('qualifications', models.TextField(blank=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('engagement_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern'), ('consultant', 'Consultant'), ('volunteer', 'Volunteer')], db_index=True, default='full_time', max_length=30)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('contract_ended', 'Contract ended'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=30)),
                ('work_location_type', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], db_index=True, default='onsite', max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('timezone_name', models.CharField(default='Asia/Colombo', max_length=100)),
                ('joined_at', models.DateField(blank=True, db_index=True, null=True)),
                ('employment_ended_at', models.DateField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('is_leadership', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_profile_usages', to='media_library.mediaasset')),
                ('reports_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='team_management.teammember')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'first_name', 'last_name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('team_type', models.CharField(choices=[('executive', 'Executive'), ('management', 'Management'), ('engineering', 'Engineering'), ('design', 'Design'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('finance', 'Finance'), ('operations', 'Operations'), ('support', 'Support'), ('hr', 'Human resources'), ('legal', 'Legal'), ('project', 'Project team'), ('custom', 'Custom')], db_index=True, default='custom', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_teams', to='team_management.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_teams', to='team_management.teammember')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMemberService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expertise_level', models.CharField(choices=[('awareness', 'Awareness'), ('working', 'Working knowledge'), ('proficient', 'Proficient'), ('expert', 'Expert'), ('lead', 'Lead specialist')], db_index=True, default='proficient', max_length=20)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='team_management.teammember')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_assignments', to='services_catalog.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_primary', 'sort_order', 'service__title'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teammember',
            name='services',
            field=models.ManyToManyField(related_name='team_members', through='team_management.TeamMemberService', to='services_catalog.service'),
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role_title', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateField(default=django.utils.timezone.localdate)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='team_management.teammember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='team_management.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-is_primary', 'sort_order', 'joined_at'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_type', 'is_active'], name='team_manage_team_ty_d331c9_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['parent', 'sort_order'], name='team_manage_parent__84e7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_public', 'sort_order'], name='team_manage_is_publ_37eba9_idx'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_active_team_name'),
        ),
        migrations.AddIndex(
            model_name='teammemberservice',
            index=models.Index(fields=['member', 'is_primary'], name='team_manage_member__b1bdd6_idx'),
        ),
        migrations.AddIndex(
            model_name='teammemberservice',
            index=models.Index(fields=['service', 'expertise_level'], name='team_manage_service_e7a445_idx'),
        ),
        migrations.AddIndex(
            model_name='teammemberservice',
            index=models.Index(fields=['is_public', 'sort_order'], name='team_manage_is_publ_d04054_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammemberservice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('member', 'service'), name='unique_active_team_member_service'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['employment_status', 'sort_order'], name='team_manage_employm_3db208_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_public', 'is_featured'], name='team_manage_is_publ_d8104a_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['reports_to', 'employment_status'], name='team_manage_reports_97dc35_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['country', 'employment_status'], name='team_manage_country_a627a8_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'is_active', 'sort_order'], name='team_manage_team_id_b2812f_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['member', 'is_primary', 'is_active'], name='team_manage_member__007225_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('team', 'member'), name='unique_active_team_membership'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False), ('is_primary', True)), fields=('member',), name='unique_active_primary_team_membership'),
        ),
    ]
