# Generated by Django 5.1.15 on 2026-08-05 21:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
        ('services_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('website', 'Website'), ('seo', 'SEO'), ('marketing', 'Marketing'), ('software', 'Software'), ('mobile_app', 'Mobile App'), ('hosting', 'Hosting'), ('maintenance', 'Maintenance'), ('consulting', 'Consulting'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('short_description', models.CharField(blank=True, max_length=350)),
                ('description', models.JSONField(blank=True, default=dict)),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed'), ('starting_from', 'Starting From'), ('custom_quote', 'Custom Quote'), ('free', 'Free')], db_index=True, default='fixed', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(db_index=True, default='LKR', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], db_index=True, default='one_time', max_length=30)),
                ('delivery_time', models.CharField(blank=True, max_length=150)),
                ('revisions_included', models.PositiveIntegerField(default=0)),
                ('support_period_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('current_revision_number', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='services_catalog.service')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='LKR', max_length=3)),
                ('billing_cycle', models.CharField(choices=[('one_time', 'One Time'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], default='one_time', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='packages_catalog.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageComparisonGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageComparisonItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_recommended', models.BooleanField(default=False)),
                ('comparison_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages_catalog.packagecomparisongroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_items', to='packages_catalog.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='packagecomparisongroup',
            name='packages',
            field=models.ManyToManyField(related_name='comparison_groups', through='packages_catalog.PackageComparisonItem', to='packages_catalog.package'),
        ),
        migrations.CreateModel(
            name='PackageFaq',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='packages_catalog.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('is_included', models.BooleanField(default=True)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='packages_catalog.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='packages_catalog.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-revision_number',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageSeo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=170)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('open_graph_title', models.CharField(blank=True, max_length=100)),
                ('open_graph_description', models.CharField(blank=True, max_length=200)),
                ('twitter_title', models.CharField(blank=True, max_length=100)),
                ('twitter_description', models.CharField(blank=True, max_length=200)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('open_graph_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_open_graph_usages', to='media_library.mediaasset')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='packages_catalog.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackageTargetAudience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_audiences', to='packages_catalog.package')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category', 'status'], name='packages_ca_categor_6dd77b_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['service', 'status'], name='packages_ca_service_487419_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_featured', 'sort_order'], name='packages_ca_is_feat_41a3d3_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['is_popular', 'sort_order'], name='packages_ca_is_popu_9048c8_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['status', 'published_at'], name='packages_ca_status_bb9f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='packageaddon',
            index=models.Index(fields=['package', 'is_active'], name='packages_ca_package_7eb9b9_idx'),
        ),
        migrations.AddIndex(
            model_name='packagecomparisonitem',
            index=models.Index(fields=['comparison_group', 'sort_order'], name='packages_ca_compari_e64efd_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagecomparisonitem',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('comparison_group', 'package'), name='unique_active_package_comparison'),
        ),
        migrations.AddIndex(
            model_name='packagefaq',
            index=models.Index(fields=['package', 'sort_order'], name='packages_ca_package_9d5301_idx'),
        ),
        migrations.AddIndex(
            model_name='packagefeature',
            index=models.Index(fields=['package', 'sort_order'], name='packages_ca_package_503bba_idx'),
        ),
        migrations.AddIndex(
            model_name='packagerevision',
            index=models.Index(fields=['package', 'revision_number'], name='packages_ca_package_2ebd1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='packagerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('package', 'revision_number'), name='unique_active_package_revision'),
        ),
        migrations.AddIndex(
            model_name='packagetargetaudience',
            index=models.Index(fields=['package', 'sort_order'], name='packages_ca_package_bb0abb_idx'),
        ),
    ]
